In [1]:
C:/Users/Ian Mwenda/Python Projects/House Pricing Prediction
    

SyntaxError: invalid syntax (<ipython-input-1-d3941f41f333>, line 1)

In [2]:
#Getting relevant libraries.

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV

In [5]:
#loading the data
df = pd.read_csv("modified_data.csv")

In [6]:
df.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    AllPub    Inside  ...             0         0           0        0   
1    AllPub       FR2  ...             0         0           0        0   
2    AllPub    Inside  ...             0         0           0        0   
3    AllPub    Corner  ...           272         0           0        0   
4    AllPub       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 77 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [8]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [9]:
df.shape

(1460, 77)

In [10]:
#dropping ID column it has no impact on the data
df.drop('Id',inplace=True,axis=1)

In [11]:
df.head(1)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  

[1 rows x 76 columns]

In [12]:
original_features=list(df.columns)
len(original_features)

76

In [13]:
#checking for columns with missing values.
features_missing_values=list(df.columns[df.isna().any()])
len(features_missing_values)

15

In [14]:
#Filling Missing Values
bfill,mean_fill=[],[]

In [15]:
for feature in features_missing_values:
  print(feature,' ',df[feature].isna().sum()/len(df)*100,' ',df[feature].dtype)
  if df[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [16]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [17]:
for feature in mean_fill:
  df[feature].fillna(df[feature].mean(),inplace=True)

In [18]:
for feature in bfill:
  df[feature].fillna(method='bfill',inplace=True)

In [19]:
#checking for missing values if any
df.columns[df.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [20]:
df['FireplaceQu'].isna().sum()

2

In [21]:
df['FireplaceQu'].fillna(method='ffill',inplace=True)

In [22]:
#Encode the dataset
categorical_features=list(df.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [23]:
numerical=list(set(original_features)-set(categorical_features))
numerical

['YrSold',
 'GrLivArea',
 'BsmtFinSF1',
 'KitchenAbvGr',
 'OverallCond',
 'YearRemodAdd',
 'OpenPorchSF',
 'BsmtFinSF2',
 'Fireplaces',
 'SalePrice',
 '3SsnPorch',
 '1stFlrSF',
 'MiscVal',
 'LotArea',
 'BsmtHalfBath',
 'BsmtUnfSF',
 'MoSold',
 'TotRmsAbvGrd',
 'LowQualFinSF',
 'HalfBath',
 'GarageYrBlt',
 'LotFrontage',
 'BedroomAbvGr',
 'MSSubClass',
 '2ndFlrSF',
 'YearBuilt',
 'WoodDeckSF',
 'FullBath',
 'BsmtFullBath',
 'OverallQual',
 'GarageArea',
 'GarageCars',
 'ScreenPorch',
 'PoolArea',
 'EnclosedPorch',
 'TotalBsmtSF',
 'MasVnrArea']

In [24]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [25]:
target=['SalePrice']

In [26]:
df_nominal=pd.get_dummies(df[nominal])

In [27]:
for feature in ordinal:
  df[feature]=df[feature].astype('category').cat.codes

df_ordinal=df[ordinal]

In [28]:
df[numerical]

YrSold  GrLivArea  BsmtFinSF1  KitchenAbvGr  OverallCond  YearRemodAdd  \
0       2008       1710         706             1            5          2003   
1       2007       1262         978             1            8          1976   
2       2008       1786         486             1            5          2002   
3       2006       1717         216             1            5          1970   
4       2008       2198         655             1            5          2000   
...      ...        ...         ...           ...          ...           ...   
1455    2007       1647           0             1            5          2000   
1456    2010       2073         790             1            6          1988   
1457    2010       2340         275             1            9          2006   
1458    2010       1078          49             1            6          1996   
1459    2008       1256         830             1            6          1965   

      OpenPorchSF  BsmtFinSF2  Fireplaces  SalePrice  ...  FullBath  \
0              61           0           0     208500  ...         2   
1               0           0           1     181500  ...         2   
2              42           0           1     223500  ...         2   
3              35           0           1     140000  ...         1   
4              84           0           1     250000  ...         2   
...           ...         ...         ...        ...  ...       ...   
1455           40           0           1     175000  ...         2   
1456            0         163           2     210000  ...         2   
1457           60           0           2     266500  ...         2   
1458            0        1029           0     142125  ...         1   
1459           68         290           0     147500  ...         1   

      BsmtFullBath  OverallQual  GarageArea  GarageCars  ScreenPorch  \
0                1            7         548           2            0   
1                0            6         460           2            0   
2                1            7         608           2            0   
3                1            7         642           3            0   
4                1            8         836           3            0   
...            ...          ...         ...         ...          ...   
1455             0            6         460           2            0   
1456             1            6         500           2            0   
1457             0            7         252           1            0   
1458             1            5         240           1            0   
1459             1            5         276           1            0   

      PoolArea  EnclosedPorch  TotalBsmtSF  MasVnrArea  
0            0              0          856       196.0  
1            0              0         1262         0.0  
2            0              0          920       162.0  
3            0            272          756         0.0  
4            0              0         1145       350.0  
...        ...            ...          ...         ...  
1455         0              0          953         0.0  
1456         0              0         1542       119.0  
1457         0              0         1152         0.0  
1458         0            112         1078         0.0  
1459         0              0         1256         0.0  

[1460 rows x 37 columns]

In [29]:
new_df=pd.concat([df_nominal,df_ordinal,df[numerical]],axis=1)

In [30]:
new_df

MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                    0            0            0            1            0   
1                    0            0            0            1            0   
2                    0            0            0            1            0   
3                    0            0            0            1            0   
4                    0            0            0            1            0   
...                ...          ...          ...          ...          ...   
1455                 0            0            0            1            0   
1456                 0            0            0            1            0   
1457                 0            0            0            1            0   
1458                 0            0            0            1            0   
1459                 0            0            0            1            0   

      LandContour_Bnk  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0                   0                0                0                1   
1                   0                0                0                1   
2                   0                0                0                1   
3                   0                0                0                1   
4                   0                0                0                1   
...               ...              ...              ...              ...   
1455                0                0                0                1   
1456                0                0                0                1   
1457                0                0                0                1   
1458                0                0                0                1   
1459                0                0                0                1   

      Neighborhood_Blmngtn  ...  FullBath  BsmtFullBath  OverallQual  \
0                        0  ...         2             1            7   
1                        0  ...         2             0            6   
2                        0  ...         2             1            7   
3                        0  ...         1             1            7   
4                        0  ...         2             1            8   
...                    ...  ...       ...           ...          ...   
1455                     0  ...         2             0            6   
1456                     0  ...         2             1            6   
1457                     0  ...         2             0            7   
1458                     0  ...         1             1            5   
1459                     0  ...         1             1            5   

      GarageArea  GarageCars  ScreenPorch  PoolArea  EnclosedPorch  \
0            548           2            0         0              0   
1            460           2            0         0              0   
2            608           2            0         0              0   
3            642           3            0         0            272   
4            836           3            0         0              0   
...          ...         ...          ...       ...            ...   
1455         460           2            0         0              0   
1456         500           2            0         0              0   
1457         252           1            0         0              0   
1458         240           1            0         0            112   
1459         276           1            0         0              0   

      TotalBsmtSF  MasVnrArea  
0             856       196.0  
1            1262         0.0  
2             920       162.0  
3             756         0.0  
4            1145       350.0  
...           ...         ...  
1455          953         0.0  
1456         1542       119.0  
1457         1152         0.0  
1458         1078         0.0  
1459         1256         0.0  

[1460 rows x 107 columns]

In [31]:
new_df.shape

(1460, 107)

In [32]:
#Standardize the dataset
new_df.drop('SalePrice',axis=1,inplace=True)

In [33]:
X=new_df.to_numpy()

In [34]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 4.000e+00,
       1.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 0.000e+00, 0.000e+00,
       4.000e+00, 2.000e+00, 4.000e+00, 2.000e+00, 0.000e+00, 8.000e+00,
       2.000e+00, 2.000e+00, 6.000e+00, 1.000e+00, 4.000e+00, 2.000e+00,
       4.000e+00, 5.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 4.000e+00,
       4.000e+00, 1.200e+01, 3.000e+00, 1.000e+00, 2.000e+00, 1.300e+01,
       3.000e+00, 5.000e+00, 1.000e+00, 2.000e+00, 2.008e+03, 1.710e+03,
       7.060e+02, 1.000e+00, 5.000e+00, 2.003e+03, 6.100e+01, 0.000e+00,
       0.000e+00, 0.000e+00, 8.560e+02, 0.000e+00, 

In [35]:
X=StandardScaler().fit_transform(X)

In [36]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888, -0.49151573,
        0.22403433, -0.12579688, -0.23012211,  0.28974476,  0.75073056,
       -0.22571613, -0.41169079,  0.2085023 , -0.40779461,  0.18797343,
       -0.03628912, -0.88465767,  0.31386709, -0.03174026, -0.29055229,
        0.25597761,  0.26381257,  0.60466978, -0.40936914,  1.11993319,
        0.30941909, -0.71775144, -0.02618016, -1.23804229,  0.36420746,
        0.303692  ,  0.74309239,  0.28780036, -0.12304604,  0.83559903,
        0.75162623,  0.64046232,  1.02668924,  0.06423821, -0.77

In [37]:
y=df[target]

In [38]:
y=y.to_numpy()

In [39]:
y=StandardScaler().fit_transform(y)

In [40]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [41]:
#Perfom feature extraction using PCA
pca=PCA(n_components=2)

In [42]:
p_components=pca.fit_transform(X)

In [43]:
p_components

array([[ 2.44330916, -1.27844478],
       [ 0.31646071,  2.63831137],
       [ 2.85722025, -0.81085284],
       ...,
       [ 1.26182387, -0.85878071],
       [-2.85096488,  3.29436665],
       [-0.77738563,  2.79075521]])

In [44]:
pca.explained_variance_ratio_

array([0.10560233, 0.04472091])